In [7]:
import numpy as np
from sklearn.datasets import fetch_california_housing


In [8]:
X,y = fetch_california_housing(return_X_y=True)

In [9]:
X[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [10]:
X.shape

(20640, 8)

In [11]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [12]:
y.shape

(20640,)

Using Sklearn's Linear Regression

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [15]:
print(X_train.shape)
print(X_test.shape)

(16512, 8)
(4128, 8)


In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
reg = LinearRegression()

In [18]:
reg.fit(X_train,y_train)

LinearRegression()

In [21]:
y_pred = reg.predict(X_test)

In [22]:
from sklearn.metrics import r2_score

In [23]:
r2_score(y_test,y_pred)


0.6013853272055167

In [24]:
reg.coef_

array([ 4.40945741e-01,  9.12556815e-03, -1.13654709e-01,  6.19465627e-01,
       -6.70834408e-06, -4.09574120e-03, -4.11981515e-01, -4.24539742e-01])

In [25]:
reg.intercept_

np.float64(-36.022830906529414)

Making our own Linear Regression Class

In [26]:
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred


In [27]:
lr = MeraLR()

In [28]:
lr.fit(X_train,y_train)

In [29]:

X_train.shape

(16512, 8)

In [30]:
np.insert(X_train,0,1,axis=1).shape

(16512, 9)

In [31]:
y_pred = lr.predict(X_test)

In [32]:
r2_score(y_test,y_pred)

0.6013853272057876

In [33]:
lr.coef_

array([ 4.40945741e-01,  9.12556815e-03, -1.13654709e-01,  6.19465627e-01,
       -6.70834408e-06, -4.09574120e-03, -4.11981515e-01, -4.24539742e-01])

In [35]:
lr.intercept_

np.float64(-36.022830907016434)